language: node_js
node_js:
  - 14
cache: npm
addons:
  chrome: stable
install:
  - npm install
git:
  depth: 3
before_script:
  - npm install -g @angular/cli
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
