language: node_js
node_js:
  - "11.0"
cache: npm
git:
  depth: 3
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - npm i
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: ./unit-tests
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
